on:
  issues:
    types:
      - opened
      - unlabeled
      - labeled
  
jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: acts-project/check-labels-action@master
        with:
          labels: Bug,Improvement,Infrastructue,New Feature
          triage_label: Triage
