on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked 
      - review_requested 
      - review_request_removed
      - assigned
      - unassigned
  
jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: acts-project/check-labels-action@master
        with:
          labels: Bug,Improvement,Infrastructue,New Feature
          triage_label: Triage
